# Generated by Django 5.1.3 on 2024-11-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beranda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='beranda/banner/')),
                ('title_1', models.CharField(max_length=255)),
                ('deskripsi_1', models.TextField()),
                ('gambar_1', models.ImageField(upload_to='beranda/gambar_1/')),
            ],
        ),
    ]
