# Generated by Django 5.1.3 on 2024-11-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0002_beranda_title_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keunggulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_2', models.ImageField(upload_to='keunggulan/')),
                ('title_2', models.CharField(max_length=255)),
                ('deskripsi_2', models.TextField()),
                ('beranda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keunggulan', to='OnKurir.beranda')),
            ],
        ),
    ]
