# Generated by Django 5.1.3 on 2024-11-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0003_keunggulan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keunggulan',
            old_name='title_2',
            new_name='title_keunggulan',
        ),
        migrations.AlterField(
            model_name='keunggulan',
            name='gambar_2',
            field=models.ImageField(upload_to='beranda/keunggulan/'),
        ),
    ]
