# Generated by Django 5.1.3 on 2024-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0005_remove_beranda_title_2_keunggulan_title_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keunggulan',
            name='title_2',
        ),
        migrations.AddField(
            model_name='beranda',
            name='title_2',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
