# Generated by Django 5.1.3 on 2024-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0006_remove_keunggulan_title_2_beranda_title_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentangKami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='TentangKami/banner/')),
                ('title_1', models.CharField(max_length=255)),
                ('deskripsi_1', models.TextField()),
                ('gambar', models.ImageField(upload_to='TentangKami/gambar/')),
                ('title_2', models.CharField(max_length=255)),
                ('deskripsi_2', models.TextField()),
                ('title_3', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='beranda',
            old_name='deskripsi_1',
            new_name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='beranda',
            name='gambar_1',
        ),
        migrations.AddField(
            model_name='beranda',
            name='gambar',
            field=models.ImageField(default='exit', upload_to='beranda/gambar/'),
            preserve_default=False,
        ),
    ]
