# Generated by Django 5.1.3 on 2024-11-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0007_tentangkami_rename_deskripsi_1_beranda_deskripsi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beranda',
            old_name='banner',
            new_name='banner_beranda',
        ),
        migrations.RenameField(
            model_name='beranda',
            old_name='deskripsi',
            new_name='deskripsi_beranda',
        ),
        migrations.RenameField(
            model_name='beranda',
            old_name='gambar',
            new_name='gambar_beranda',
        ),
        migrations.RenameField(
            model_name='beranda',
            old_name='title_1',
            new_name='title_beranda',
        ),
        migrations.RenameField(
            model_name='beranda',
            old_name='title_2',
            new_name='title_keunggulan',
        ),
        migrations.RenameField(
            model_name='keunggulan',
            old_name='deskripsi_2',
            new_name='deskripsi_keunggulan',
        ),
        migrations.RenameField(
            model_name='keunggulan',
            old_name='gambar_2',
            new_name='gambar_keunggulan',
        ),
        migrations.RenameField(
            model_name='tentangkami',
            old_name='banner',
            new_name='banner_TentangKami',
        ),
        migrations.RenameField(
            model_name='tentangkami',
            old_name='deskripsi_1',
            new_name='deskripsi_TentangKami',
        ),
        migrations.RenameField(
            model_name='tentangkami',
            old_name='deskripsi_2',
            new_name='deskripsi_VisiMisi',
        ),
        migrations.RenameField(
            model_name='tentangkami',
            old_name='gambar',
            new_name='gambar_TentangKami',
        ),
        migrations.RenameField(
            model_name='tentangkami',
            old_name='title_1',
            new_name='title_TentangKami',
        ),
        migrations.RenameField(
            model_name='tentangkami',
            old_name='title_2',
            new_name='title_VisiMisi',
        ),
        migrations.RenameField(
            model_name='tentangkami',
            old_name='title_3',
            new_name='title_tim',
        ),
    ]
