# Generated by Django 5.1.3 on 2024-11-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0009_rename_title_keunggulan_keunggulan_title_isikeunggulan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_tim', models.ImageField(upload_to='beranda/keunggulan/')),
                ('nama_tim', models.CharField(max_length=255)),
                ('jabatan_tim', models.CharField(max_length=255)),
                ('tentangkami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tim', to='OnKurir.tentangkami')),
            ],
        ),
    ]
