# Generated by Django 5.1.3 on 2024-11-16 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0010_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tim',
            name='gambar_tim',
            field=models.ImageField(upload_to='TentangKami/Tim/'),
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='beranda/banner/')),
                ('beranda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='OnKurir.beranda')),
            ],
        ),
    ]
