# Generated by Django 5.1.3 on 2024-11-16 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0011_alter_tim_gambar_tim_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beranda',
            name='banner_beranda',
        ),
    ]
