# Generated by Django 5.1.3 on 2024-11-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0012_remove_beranda_banner_beranda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='image',
            new_name='banner_beranda',
        ),
    ]
