# Generated by Django 5.1.3 on 2024-11-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0013_rename_image_carousel_banner_beranda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='banner_beranda',
            new_name='image',
        ),
    ]
