# Generated by Django 5.1.3 on 2024-11-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0014_rename_banner_beranda_carousel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='image',
            new_name='banner_beranda',
        ),
    ]
