# Generated by Django 5.1.3 on 2024-11-16 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0015_rename_image_carousel_banner_beranda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_Galeri', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IsiGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_galeri', models.ImageField(upload_to='Galeri/')),
                ('galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isi_galeri', to='OnKurir.galeri')),
            ],
        ),
    ]
