# Generated by Django 5.1.3 on 2024-11-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0016_galeri_isigaleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_layanan', models.CharField(max_length=255)),
            ],
        ),
    ]
