# Generated by Django 5.1.3 on 2024-11-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0017_layanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='title_carakerja',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IsiLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_layanan', models.ImageField(upload_to='Layanan/')),
                ('Jenis_layanan', models.CharField(max_length=255)),
                ('deskripsi_layanan', models.TextField()),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isi_layanan', to='OnKurir.layanan')),
            ],
        ),
    ]
