# Generated by Django 5.1.3 on 2024-11-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0018_layanan_title_carakerja_isilayanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='isilayanan',
            name='kebijakan_ketentuan',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isilayanan',
            name='proses_pengiriman',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
