# Generated by Django 5.1.3 on 2024-11-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0019_isilayanan_kebijakan_ketentuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='title_KebijakanKetentuan',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layanan',
            name='title_ProsesPengiriman',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
