# Generated by Django 5.1.1 on 2024-11-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0022_blog_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
