# Generated by Django 5.1.1 on 2024-11-20 04:36

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0024_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
