# Generated by Django 5.1.1 on 2024-11-20 18:56

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0027_footermedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontakKami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_TentangKami', models.ImageField(upload_to='KontakKami/banner/')),
                ('judul', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='KontakList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(choices=[('bi bi-envelope', 'E-mail'), ('bi bi-telephone', 'Telp'), ('bi bi-map', 'Alamat')], default='bi bi-envelope', max_length=255, unique=True)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='footermedia',
            name='media',
            field=models.CharField(choices=[('bi bi-facebook', 'FaceBook'), ('bi bi-youtube', 'YouTube'), ('bi bi-instagram', 'Instagram'), ('bi bi-whatsapp', 'Whatsapp')], default='bi bi-facebook', max_length=255, unique=True),
        ),
    ]
