# Generated by Django 5.1.1 on 2024-11-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnKurir', '0028_kontakkami_kontaklist_alter_footermedia_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontakkami',
            old_name='banner_TentangKami',
            new_name='banner',
        ),
    ]
